### PR TITLE
Update firstday database script.sql

### PR DESCRIPTION
**Pull request by cheesecrackers2544**
Updated the 'Listings' Table to align with the data we have available.

### CODE REVIEW

**Review by BenjiPiper — APPROVED** [review]
approved

**Review by BenjiPiper — APPROVED** [review]
approved

**Review by BenjiPiper — APPROVED** [review]
approved

**Review by BenjiPiper — APPROVED** [review]
aaprroved

**Review by BenjiPiper — APPROVED** [review]
approv3e

**Review by BenjiPiper — APPROVED** [review]

**Review by BenjiPiper — APPROVED** [review]
approved via codespace

**Comment by cheesecrackers2544** [comment]
looks good

**Pull request merged**
